# Config file for automatic testing at travis-ci.org
dist: xenial

language: python
python:
  - 3.7.3

# Command to install dependencies, e.g. pip install -r requirements_dev.txt --use-mirrors
install:
  - pip install -r requirements_dev.txt
  - python manage.py migrate

env:
  - DJANGO_SETTINGS_MODULE=vgbrowser.settings

# Command to run tests, e.g. python setup.py test
script:
  - python manage.py test