# Generated by Django 2.2.1 on 2019-08-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphGenome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('seq', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graph.GraphGenome')),
            ],
            options={
                'unique_together': {('graph', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=1000, unique=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graph.GraphGenome')),
            ],
        ),
        migrations.CreateModel(
            name='NodeTraversal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='Defines the order a path lists traversals')),
                ('strand', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=1)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graph.Node')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graph.Path')),
            ],
        ),
    ]
