# Generated by Django 2.2.1 on 2019-08-22 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Graph', '0002_Path_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='summarized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Graph.Node'),
        ),
        migrations.AddField(
            model_name='path',
            name='zoom',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='nodetraversal',
            name='order',
            field=models.IntegerField(help_text='Defines the order a path lists traversals. The scale of order is not preserved between zoom levels.'),
        ),
        migrations.AlterUniqueTogether(
            name='path',
            unique_together={('graph', 'accession', 'zoom')},
        ),
        migrations.AddField(
            model_name='path',
            name='summarized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_child', to='Graph.Path'),
        ),
    ]
