# Generated by Django 2.2.1 on 2019-08-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('Graph', '0004_ZoomLevel_objects'), ('Graph', '0005_auto_20190823_1603')]

    dependencies = [
        ('Graph', '0003_add_zoom_levels'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='path',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='path',
            name='graph',
        ),
        migrations.RemoveField(
            model_name='path',
            name='zoom',
        ),
        migrations.CreateModel(
            name='ZoomLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom', models.IntegerField(default=0)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graph.GraphGenome')),
                ('paths', models.ManyToManyField(blank=True, help_text='One path for each accession in a zoom level.  Paths can be reused unmodified in multiple levels.', related_name='zoom_levels', to='Graph.Path')),
            ],
            options={
                'unique_together': {('graph', 'zoom')},
            },
        ),
    ]
