# Generated by Django 2.2.1 on 2019-09-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Graph', '0004_ZoomLevel_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='zoom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Graph.ZoomLevel'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('zoom', 'name')},
        ),
        migrations.RemoveField(
            model_name='node',
            name='graph',
        ),
    ]
