# Generated by Django 2.2.1 on 2019-09-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Graph', '0005_Node_zoomlevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoomlevel',
            name='paths',
        ),
        migrations.AddField(
            model_name='path',
            name='zoom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Graph.ZoomLevel'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='path',
            unique_together={('accession', 'zoom')},
        ),
    ]
