# Generated by Django 2.2.1 on 2019-09-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Graph', '0007_NodeTraversal_unique_together_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='summarized_by',
        ),
    ]
