# Generated by Django 2.2.1 on 2019-07-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HaploBlocker.Node')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HaploBlocker.Path')),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['path', 'id'],
            },
        ),
    ]
